version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers

    steps:
      - checkout
      - run: sudo npm install -g @angular/cli

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - "node_modules"

      - run: ng lint
      - run: ng test --watch false --reporters progress,junit
      - store_test_results:
          path: test-reports/junit

      - run:
          name: Deploy
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                ng build --prod
                cp .circleci/master-readme.md dist/paulshields/README.md
                npx angular-cli-ghpages --dir=dist/paulshields/ --branch=master --repo=https://${GH_TOKEN}@github.com/Pkshields/pkshields.github.io.git --name=${GH_COMMIT_NAME} --email=${GH_COMMIT_EMAIL}
              fi
